version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: local_pgdb
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    ports:
      - "8888:80"
    env_file:
      - .env
    volumes:
      - pgadmin-data:/var/lib/pgadmin


volumes:
  local_pgdata:
  pgadmin-data:

    