"""add Task model

Revision ID: 231598aad168
Revises: 
Create Date: 2024-02-05 17:23:00.061323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '231598aad168'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('done', 'doing', 'planned', name='status'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
